import alterarCores from "./alterarCores.js";
import controlarRadios from "./exibirConteudosRadio.js";
import multiStep from "./multiStep.js";
import submitForm from "./enviarFormulario.js";
import verificarAcesso from "./login.js";
controlarRadios();
alterarCores();
multiStep();
submitForm();
verificarAcesso();